# Define base image
FROM postgres:latest

# In case we want to initialise the database with .sql or .sh scripts, we can
# simply copy those files in /docker-entrypoint-initdb.d/ 
# Please refer to the official documentation for official details under
#
# https://hub.docker.com/_/postgres
# -> Section Initialization Scripts
#COPY *.sql /docker-entrypoint-initdb.d/
