version: '2.0'

services:
    database:
        build:
            context: ./PostgreSQL/
            dockerfile: ./Dockerfile
        environment:
            POSTGRES_PASSWORD: Test12345! 
        ports:
            - 5432:5432
        networks:
            - net

    tgwebapp:
        build:
            context: ./Pillepalle1.TelegramWebapp/
            dockerfile: ./Dockerfile
        networks:
            - net

    nginx:
        build:
            context: ./nginx/
            dockerfile: ./Dockerfile
        ports:
            - 80:80
        depends_on:
            - tgwebapp
        networks:
            - net

networks:
    net:
        driver: bridge
