version: '2.0'

services:
    database:
        build:
            context: ./database/
            dockerfile: ./Dockerfile
        environment:
            POSTGRES_PASSWORD: "${PGPASS}"
        volumes:
            - ./.vol/pqsql:/var/lib/postgresql/data

    certbot:
        build:
            context: ./certbot/
            dockerfile: ./Dockerfile
        environment:
            EMAIL: "${EMAIL}" 
            FQDN: "${FQDN}" 
        ports:
            - 80:80
        volumes:
            - ./.vol/letsencrypt:/etc/letsencrypt
